# UI + application coordination

import streamlit as st

from api.client import assess_application

# Readiness Constants

HIGH_READINESS_THRESHOLD = 80
MODERATE_READINESS_THRESHOLD = 60



# Readiness classification

def get_readiness_info(score):
    if score >= HIGH_READINESS_THRESHOLD:
        return (
            "High Readiness",
            "The application appears well positioned for "
            "cloud migration with relatively few readiness concerns."
        )

    elif score >= MODERATE_READINESS_THRESHOLD:
        return (
            "Moderate Readiness",
            "The application has some cloud migration "
            "considerations that should be addressed before migration."
        )

    else:
        return (
            "Low Readiness",
            "The application has several readiness concerns "
            "that should be addressed before migration."
        )

# ---------------------------------------------------------
# Page Configuration
# ---------------------------------------------------------

# Streamlit UI

st.set_page_config(
    page_title="Cloud Migration & Solution Advisor",
    page_icon="☁️",
    layout="wide"
)


# ---------------------------------------------------------
# Header
# ---------------------------------------------------------

st.title("Cloud Migration & Solution Advisor")

st.write(
    "Assess application requirements, identify common migration risks, "
    "and receive preliminary Azure service recommendations."
)

st.divider()


# ---------------------------------------------------------
# Application Information
# ---------------------------------------------------------

st.header("Application Assessment")

st.subheader("1. Application Information")

col1, col2 = st.columns(2)

with col1:
    application_type = st.selectbox(
        "Application Type",
        [
            "E-commerce",
            "Education",
            "Healthcare",
            "Finance",
            "Enterprise Application",
            "Other"
        ],
        help="Select the category that best describes the application."
    )

with col2:
    users = st.number_input(
        "Expected Number of Users",
        min_value=100,
        max_value=1000000,
        value=10000,
        step=1000,
        help="Enter the expected number of users the application needs to support."
    )


st.subheader("2. Current Environment")

col1, col2 = st.columns(2)

with col1:
    infrastructure = st.selectbox(
        "Current Infrastructure",
        [
            "On-Premise",
            "Cloud",
            "Hybrid"
        ],
        help="Select where the application is currently hosted."
    )

with col2:
    database = st.selectbox(
        "Database",
        [
            "PostgreSQL",
            "MySQL",
            "SQL Server",
            "None"
        ],
        help="Select the primary database technology used by the application."
    )


st.subheader("3. Performance & Availability")

col1, col2 = st.columns(2)

with col1:
    traffic = st.selectbox(
        "Expected Traffic",
        [
            "Low",
            "Medium",
            "High"
        ],
        help="Estimate the typical traffic level generated by the application."
    )

with col2:
    availability = st.selectbox(
        "Availability Requirement",
        [
            "99%",
            "99.9%",
            "99.99%"
        ],
        help="Select the required percentage of time the application should remain available."
    )


st.subheader("4. Security & Storage")

col1, col2 = st.columns(2)

with col1:
    security = st.selectbox(
        "Security Requirement",
        [
            "Low",
            "Medium",
            "High"
        ],
        help="Estimate the level of security and access-control requirements for the application."
    )

with col2:
    storage = st.selectbox(
        "Storage Requirement",
        [
            "Less than 500 GB",
            "500 GB - 2 TB",
            "More than 2 TB"
        ],
        help="Select the approximate amount of application data that needs to be stored."
    )

st.divider()


# ---------------------------------------------------------
# Analyze Button
# ---------------------------------------------------------

if st.button("Analyze Application", type="primary"):

    with st.spinner("Analyzing application..."):
        try:
            data = {
                "application_type": application_type,
                "users": users,
                "infrastructure": infrastructure,
                "database": database,
                "traffic": traffic,
                "availability": availability,
                "security": security,
                "storage": storage
            }

            assessment = assess_application(data)

            requirements = assessment["requirements"]
            risks = assessment["risks"]
            recommendations = assessment["recommendations"]
            migration_plan = assessment["migration_plan"]
            scoring = assessment["scoring"]
            score = scoring["overall_score"]


        except Exception as e:
            st.error("The assessment could not be completed.")
            st.exception(e)
            st.stop()

    readiness_level, readiness_message = get_readiness_info(score)

    st.success("Assessment completed successfully.")




    # -----------------------------------------------------
    # Results
    # -----------------------------------------------------

    st.header("Assessment Results")

    st.write(
        "The assessment below summarizes the application's cloud readiness, "
        "identified risks, technical requirements, Azure recommendations, "
        "and migration roadmap."
    )

    score_col, risk_col = st.columns(2)

    with score_col:

        st.metric(
            "Cloud Readiness Score",
            f"{score}/100"
        )

    with risk_col:

        st.metric(
            "Risks Identified",
            len(risks)
        )
    st.info(
        f"**{readiness_level}**\n\n"
        f"{readiness_message}"
    )

    st.subheader("Readiness Breakdown")

    breakdown = {
        "Infrastructure": scoring["infrastructure"],
        "Scalability": scoring["scalability"],
        "Availability": scoring["availability"],
        "Security": scoring["security"],
        "Storage": scoring["storage"],
        "Database": scoring["database"]
    }

    for dimension, dimension_score in breakdown.items():
        st.write(f"**{dimension}:** {dimension_score}/100")

    st.divider()

    # -----------------------------------------------------
    # Technical Requirements
    # -----------------------------------------------------

    st.subheader("Technical Requirements")

    if requirements:
        for requirement in requirements:
            st.markdown(
                f"**{requirement['category']}**  \n"
                f"{requirement['requirement']}"
            )
    else:
        st.info("No additional technical requirements identified.")

    st.divider()


    # -----------------------------------------------------
    # Risk Assessment
    # -----------------------------------------------------

    st.subheader("Risk Assessment")

    if risks:
        for risk in risks:

            severity = risk["severity"].upper()

            risk_text = (
                f"**{severity} — {risk['category']}**\n\n"
                f"**Reason**\n\n"
                f"{risk['reason']}\n\n"
                f"**Mitigation**\n\n"
                f"{risk['mitigation']}"
            )

            if risk["severity"] == "High":
                st.error(risk_text)
            else:
                st.warning(risk_text)

    else:
        st.success("No major risks identified.")

    st.divider()


    # -----------------------------------------------------
    # Azure Recommendations
    # -----------------------------------------------------

    st.subheader("Azure Recommendations")

    if recommendations:
        for recommendation in recommendations:
            st.markdown(
                f"### {recommendation['azure_service']}"
            )

            st.markdown(
                f"**Requirement**  \n"
                f"{recommendation['requirement']}"
            )

            st.markdown(
                f"**Why this is recommended**  \n"
                f"{recommendation['reason']}"
            )


    else:
        st.info("No Azure recommendations identified.")

    st.divider()



    # -----------------------------------------------------
    # Migration Roadmap
    # -----------------------------------------------------

    st.subheader("Migration Roadmap")

    st.write(
        "The following phases provide a structured path "
        "for migrating the application to the cloud."
    )

    if migration_plan:
        for step in migration_plan:
            st.markdown(
                f"### {step['phase']}"
            )

            st.write(step["activities"])


    else:
        st.info("No migration plan available.")
